default_language_version:
  python: python3.9

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py39-plus
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff --format=github --select=E9,F63,F7,F82 --target-version=py39 pytorch_finufft
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: darglint
        name: darglint
        entry: ruff --format=github --select=E9,F63,F7,F82 --target-version=py39 pytorch_finufft
        types: [python]
        language: system
