# This file contains values from Cookiecutter

default_context:
  project_name: "pytorch-finufft"
  project_description: "Pytorch bindings for the FINUFFT Library"
  organization: "Flatiron Institute"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "flatironinstitute"
  email: "bward@flatironinstitute.org"
  version: "0.0.0"
  line_length: "88"
  create_example_template: "none"
