FROM nvidia/cuda:12.0.0-devel-ubuntu22.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      python3 \
      python3-pip \
      cmake && \
    rm -rf /var/lib/apt/lists/*
