pipeline {
  agent none
  options {
    disableConcurrentBuilds(abortPrevious: true)
    buildDiscarder(logRotator(numToKeepStr: '8', daysToKeepStr: '20'))
    timeout(time: 1, unit: 'HOURS')
  }
  stages {
    stage('CUDA Tests') {
      agent {
         dockerfile {
            filename 'ci/Dockerfile-cuda12.0'
            args '--gpus 2'
            label 'docker && v100'
         }
      }
      environment {
    HOME = "$WORKSPACE"
      }
      steps {

    sh 'python3 -m venv $HOME'
    sh label: "set up virtual environment", script: '''#!/bin/bash -ex
      source $HOME/bin/activate
      python3 -m pip install --upgrade pip
      # we could also move pytorch install inside docker
      python3 -m pip install "torch~=2.1.0" --index-url https://download.pytorch.org/whl/cu118

      python3 -m pip install -e .[dev,cuda]
    '''
    sh label: "run tests", script: '''#!/bin/bash -ex
      source $HOME/bin/activate
      python3 -m pytest -k "cuda" tests/ --cov=pytorch_finufft -v --error-for-skips
    '''
      }
    }
  }
  post {
    failure {
      emailext subject: '$PROJECT_NAME - Build #$BUILD_NUMBER - $BUILD_STATUS',
           body: '''$PROJECT_NAME - Build #$BUILD_NUMBER - $BUILD_STATUS

Check console output at $BUILD_URL to view full results.

Building $BRANCH_NAME for $CAUSE
$JOB_DESCRIPTION

Chages:
$CHANGES

End of build log:
${BUILD_LOG,maxLines=200}
''',
           recipientProviders: [
         [$class: 'DevelopersRecipientProvider'],
           ],
           replyTo: '$DEFAULT_REPLYTO',
           to: 'bward@flatironinstitute.org'
    }
  }
}
