name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mypy_ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4.6.1
      with:
        python-version: "3.11"

    - name: Set up cache
      uses: actions/cache@v3.3.1
      with:
        path: .venv
        key: venv-${{ hashFiles('pyproject.toml', 'requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .

    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff --output-format=github --select=E9,F63,F7,F82 --target-version=py37 pytorch_finufft
        # default set of ruff rules with GitHub Annotations
        ruff --output-format=github --target-version=py37 pytorch_finufft

    - name: Lint with mypy
      run: |
        mypy pytorch_finufft/

