name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# only run on latest commit
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]

    - name: Pytest
      run: |
        pytest tests/ --cov


  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]

    - name: Check formatting
      run: |
        isort --check .
        black --check .

    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ruff --output-format=github --select=E9,F63,F7,F82 --target-version=py37 pytorch_finufft
        # default set of ruff rules with GitHub Annotations
        ruff --output-format=github --target-version=py37 pytorch_finufft

    - name: Lint with mypy
      run: |
        mypy pytorch_finufft/


  doc-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r docs/requirements.txt
        python -m pip install --no-deps -e .

    - name: Check docs
      env:
        SPHINXOPTS: "-Wq --keep-going -D plot_gallery=0"
      run: |
        cd docs/
        make clean
        make linkcheck
